### ISSUE TITLE
Set up automatic deploys

### ISSUE THREAD

**Issue by jneen** [rouge-ruby/rouge.jneen.net#27]
It would be nice if it were a lot easier to keep this app up-to-date without having to muck around so much with heroku!

**Comment by edwardloveall** [comment]
Okay, so to do this I need to have admin access to the repo. As far as I know, the only way that can happen is if it's in an org that I have access to. If you keep it on your personal account (which is fine) you'll have to setup auto deploys yourself.

If you want to do that, go to Heroku, click on the rouge app, then `Deploy` in the top tab bar, then `GitHub`. Enter `rouge.jneen.net` and turn on automatic deploys from the `master` branch. That's pretty much it, I believe.

**Comment by pyrmont** [comment]
I've set this up as part of connecting [rouge-ruby/dingus](https://github.com/rouge-ruby/dingus/) to Heroku. Deploys to the master branch will automatically trigger deployments to the new Heroku app.
