### ISSUE TITLE
The database is getting full

### ISSUE THREAD

**Issue by edwardloveall** [rouge-ruby/rouge.jneen.net#33]
Just got an email from Heroku this morning saying our database is approaching full. We have a 10,000 capacity and we're at about 75% of it.

I see three options:

1. Deploy the site on somewhere not heroku (bare linux box or another PaaS)
2. Pay Heroku $9/month for 10,000,000 rows.
3. Delete some old data to buy ourselves more time.

I'm not a fan of 3. I thought the point of saving the code bits was so people could reference them indefinitely. It also just seems annoying to go prune data every so often. 1 or 2 is fine with me.

We don't get massive traffic every day so we have some time to decide.

**Comment by edwardloveall** [comment]
Another solution could be that we host _just_ the DB elsewhere. I'm not sure if that actually works, and what happens when we need to migrate? I assume rails can deal with that just fine. I've just never done it.

**Comment by pyrmont** [comment]
This has been solved as part of the design of [rouge-ruby/dingus](https://github.com/rouge-ruby/dingus):

- an encrypted copy of the old database is kept in the repo, decrypted on load and used by the app to return data for the old pastes;
- new pastes are possible by encoding the source code into the URL string.

This creates a maximum length for the new pastes but is considered acceptable given the intended use is for short snippets of code.

Sorry it took so long, @edwardloveall :( Thank you for the suggestions!
